-- CareShield patient isolation migration
-- Run manually in Supabase SQL Editor after reviewing.
-- Safe to re-run: uses IF NOT EXISTS / conditional alters where possible.
--
-- NOTE: There is no login/auth table in the app today. We introduce a minimal
-- `accounts` row as the family/home tenant. The Streamlit app uses
-- CARESHIELD_ACCOUNT_ID (optional env var) matching the UUID below.

create extension if not exists "pgcrypto";

-- ── Fixed IDs for the default demo family (override via env in app if needed) ──
-- Default account: 00000000-0000-4000-8000-000000000001
-- Default patient: 00000000-0000-4000-8000-000000000002

create table if not exists public.accounts (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'CareShield family account',
  created_at timestamptz not null default now()
);

insert into public.accounts (id, name)
values ('00000000-0000-4000-8000-000000000001'::uuid, 'CareShield family account')
on conflict (id) do nothing;

create table if not exists public.patients (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references public.accounts (id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create index if not exists patients_account_id_idx
  on public.patients (account_id);

insert into public.patients (id, account_id, name)
values (
  '00000000-0000-4000-8000-000000000002'::uuid,
  '00000000-0000-4000-8000-000000000001'::uuid,
  'Patient'
)
on conflict (id) do nothing;

-- Conditions were session-only in the app; persist them per patient going forward.
create table if not exists public.patient_conditions (
  id bigint generated by default as identity primary key,
  patient_id uuid not null references public.patients (id) on delete cascade,
  name text not null,
  since text not null default '',
  badge text not null default 'chronic',
  created_at timestamptz not null default now()
);

create index if not exists patient_conditions_patient_id_idx
  on public.patient_conditions (patient_id);

-- ── patient_plan: discharge documents + medication envelope JSON ────────────
alter table public.patient_plan
  add column if not exists patient_id uuid references public.patients (id) on delete cascade;

update public.patient_plan
set patient_id = '00000000-0000-4000-8000-000000000002'::uuid
where patient_id is null;

create index if not exists patient_plan_patient_id_idx
  on public.patient_plan (patient_id);

-- ── medication_references: pill registration photos ───────────────────────────
alter table public.medication_references
  add column if not exists patient_id uuid references public.patients (id) on delete cascade;

update public.medication_references
set patient_id = '00000000-0000-4000-8000-000000000002'::uuid
where patient_id is null;

create index if not exists medication_references_patient_id_idx
  on public.medication_references (patient_id);

-- ── shift_logs: handover / chat / MedCam events ─────────────────────────────
alter table public.shift_logs
  add column if not exists patient_id uuid references public.patients (id) on delete cascade;

update public.shift_logs
set patient_id = '00000000-0000-4000-8000-000000000002'::uuid
where patient_id is null;

create index if not exists shift_logs_patient_id_idx
  on public.shift_logs (patient_id);

-- ── medication_logs: already has patient_id (text) — normalize to uuid ───────
-- Existing app used text values like 'default'. Backfill before type change.

update public.medication_logs
set patient_id = '00000000-0000-4000-8000-000000000002'
where patient_id is null
   or patient_id = ''
   or patient_id = 'default';

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'medication_logs'
      and column_name = 'patient_id'
      and data_type <> 'uuid'
  ) then
    alter table public.medication_logs
      alter column patient_id type uuid
      using patient_id::uuid;
  end if;
exception
  when others then
    raise notice 'Could not alter medication_logs.patient_id to uuid automatically: %', sqlerrm;
    raise notice 'If patient_id is already uuid, you can ignore this.';
end $$;

alter table public.medication_logs
  drop constraint if exists medication_logs_patient_id_fkey;

alter table public.medication_logs
  add constraint medication_logs_patient_id_fkey
  foreign key (patient_id) references public.patients (id) on delete cascade;

update public.medication_logs
set patient_id = '00000000-0000-4000-8000-000000000002'::uuid
where patient_id is null;

-- ── RLS (match existing open policies used in medication_logs.sql) ──────────
alter table public.accounts enable row level security;
alter table public.patients enable row level security;
alter table public.patient_conditions enable row level security;

drop policy if exists "Allow all access to accounts" on public.accounts;
create policy "Allow all access to accounts"
  on public.accounts for all using (true) with check (true);

drop policy if exists "Allow all access to patients" on public.patients;
create policy "Allow all access to patients"
  on public.patients for all using (true) with check (true);

drop policy if exists "Allow all access to patient_conditions" on public.patient_conditions;
create policy "Allow all access to patient_conditions"
  on public.patient_conditions for all using (true) with check (true);

-- ── Verification queries (optional — run after migration) ───────────────────
-- select * from public.accounts;
-- select * from public.patients;
-- select count(*) as patient_plan_rows, patient_id from public.patient_plan group by patient_id;
-- select count(*) as shift_log_rows, patient_id from public.shift_logs group by patient_id;
