-- Run this in Supabase: SQL Editor → New query → paste → Run

create table if not exists public.medication_logs (
  id bigint generated by default as identity primary key,
  patient_id text,
  medication_name text not null,
  scheduled_time text not null,
  status text not null check (status in ('taken', 'missed')),
  logged_at timestamptz not null default now(),
  caregiver_id text,
  notes text default ''
);

create index if not exists medication_logs_patient_id_idx
  on public.medication_logs (patient_id);

create index if not exists medication_logs_logged_at_idx
  on public.medication_logs (logged_at desc);

alter table public.medication_logs enable row level security;

drop policy if exists "Allow all access to medication_logs" on public.medication_logs;
create policy "Allow all access to medication_logs"
  on public.medication_logs
  for all
  using (true)
  with check (true);
