-- Durable per-patient care reports and chat history for Report & Ask + Handover.
-- Run manually in Supabase SQL Editor after reviewing.

create table if not exists public.patient_care_reports (
  id bigint generated by default as identity primary key,
  patient_id uuid not null references public.patients (id) on delete cascade,
  caregiver_id text,
  caregiver_name text not null default '',
  source text not null default 'voice_report',
  report_text text not null default '',
  summary text not null default '',
  severity text not null default 'monitor',
  reported_at timestamptz not null,
  photo_finding text,
  photo_type text,
  has_photo boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists patient_care_reports_patient_reported_idx
  on public.patient_care_reports (patient_id, reported_at desc);

create table if not exists public.patient_care_report_photos (
  report_id bigint primary key references public.patient_care_reports (id) on delete cascade,
  image_b64 text not null
);

create table if not exists public.patient_chat_threads (
  patient_id uuid primary key references public.patients (id) on delete cascade,
  messages jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.patient_care_reports enable row level security;
alter table public.patient_care_report_photos enable row level security;
alter table public.patient_chat_threads enable row level security;

drop policy if exists "Allow all access to patient_care_reports" on public.patient_care_reports;
create policy "Allow all access to patient_care_reports"
  on public.patient_care_reports for all using (true) with check (true);

drop policy if exists "Allow all access to patient_care_report_photos" on public.patient_care_report_photos;
create policy "Allow all access to patient_care_report_photos"
  on public.patient_care_report_photos for all using (true) with check (true);

drop policy if exists "Allow all access to patient_chat_threads" on public.patient_chat_threads;
create policy "Allow all access to patient_chat_threads"
  on public.patient_chat_threads for all using (true) with check (true);
